name: Code Inspector Analysis

on: [push]

jobs:
  check-quality:
    runs-on: ubuntu-latest
    name: Check code quality
    steps:
      - name: Check code meets quality standards
        id: code-inspector
        uses: codeinspectorio/github-action@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          code_inspector_access_key: ${{ secrets.CODE_INSPECTOR_ACCESS_KEY }}
          code_inspector_secret_key: ${{ secrets.CODE_INSPECTOR_SECRET_KEY }}
          min_quality_grade: 'GOOD'
          min_quality_score: '75'
          max_defects_rate: '0.02'
          max_complex_functions_rate: '0.0001'
          max_long_functions_rate: '.5'
          project_name: ''
          max_timeout_sec: '600'
